[project]
name = "super-mega-data-gatherer"
version = "0.1.0"
description = "Gathers support data for the Super Mega Dashboard"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.129.0",
]
